# Site settings
title: Server, Linux, Software, Hardware
email: do-not-use@email.tld
description: "Monitoring and metrics"  
baseurl: "/"
url: "https://opentokix.github.io"
twitter_username: opentokix
github_username:  opentokix

# Build settings
markdown: kramdown
permalink: pretty
source: /home/peter/src/blog
destination: /home/peter/src/opentokix.github.io
